services:
  db:
     image: "mcr.microsoft.com/mssql/server"
     environment:
         SA_PASSWORD: "Mydb_password123"
         ACCEPT_EULA: "Y"

  frontend: 
    image: jpcostadev/oab-app:v1
    ports:
      - "4200:80"
    depends_on:
      - api

  api:
    image: jpcostadev/api:v1
    ports: 
      - "81:81"
    volumes:
       - /c/temp-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
    restart: always

