services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "OcP2020123"
      ACCEPT_EULA: "Y"
    ports:
      - "1450:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
    networks:
      - networks

  frontend: 
    image: jpcostadev/oab-app:v1
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - networks

  api:
    image: jpcostadev/api:v3
    environment:
      DbServer: mssql-server
      DbPort: "1450"
      DbUser: "SA"
      Password: "OcP2020123"
      Database: "Oab010"
    ports: 
      - "81:81"
    depends_on:
      - mssql-server
    networks:
      - networks

networks:
  networks: